# Generated by Django 3.2.9 on 2021-12-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True, verbose_name='time')),
                ('temp', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='temp')),
                ('light', models.IntegerField(verbose_name='light')),
                ('humidity', models.IntegerField(verbose_name='humidity')),
            ],
        ),
    ]
